---
baseurl : "http://www.tomtosseyn.be/"
title : "Tom Tosseyn"
languageCode: "en-us"
preserveTaxonomyNames: true
pluralizelisttitles: false
params:
  description: "Graphic design, logo development, concept design, artdirecting and consultancy for fashion & print."
  themeColor: "#111"
  og:
    title: "Tom Tosseyn"
    description: "Graphic design, logo development, concept design, artdirecting and consultancy for fashion & print."
    image: "https://s3-eu-west-1.amazonaws.com/www.tomtosseyn.be/staging/images/share-image.png"
MetaDataFormat: yaml

---
